# Generated by Django 3.0.3 on 2020-04-03 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название поста')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 4, 3, 15, 40, 58, 53044, tzinfo=utc), verbose_name='Дата создания поста')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
