# Generated by Django 3.0.3 on 2020-04-03 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200403_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 17, 17, 20, 755857, tzinfo=utc)),
        ),
    ]
