# Generated by Django 3.0.2 on 2020-08-07 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 20, 5, 57, 434058, tzinfo=utc), verbose_name='Дата создания поста'),
        ),
    ]
